site_name: My Succulents
nav:
  - Home: index.md
  - Genus:
    - Haworthia: Genus/Haworthia.md
    - Lithops: Genus/Lithops.md
  - Growing Medium: 
theme:
  name: material
  features:
    - navigation.tabs