site_name: My Succulents
nav:
  - Home: index.md
  - Genus:
    - Haworthia: Genus/Haworthia.md
    - Lithops: Genus/Lithops.md
  - Growing Medium: growing_medium.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
- attr_list
